# Change these first
owner: EverythingSuckz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: File Stream Server
    url: https://invalid.gq/status
    icon: https://invalid.gq/favicon.ico

assignees:
  - EverythingSuckz
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: "**Monitors the Upptime** of my sites."
  introMessage: This is an instance [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: File Stream Bot
      href: https://telegram.dog/RapidStreamBot
  theme: night
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
